name = "bearingDistributions"
uuid = "97025544-dab9-4480-a8b9-82989a134056"
authors = ["Alex Buck <alexjbuck@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
